# Generated by Django 6.0.5 on 2026-05-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsManagement', '0002_finance_player_team_delete_animal_delete_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='team',
            field=models.CharField(max_length=100),
        ),
    ]
